[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd printmechecks && npm ci"]

[phases.build]
cmds = ["cd printmechecks && npm run build"]

[start]
cmd = "cd printmechecks && npm run preview -- --host 0.0.0.0 --port $PORT"
