import { createClient } from '@supabase/supabase-js'

// Supabase configuration
const supabaseUrl = 'https://cffhvhgvaidwofyceoju.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmZmh2aGd2YWlkd29meWNlb2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODUwOTMsImV4cCI6MjA3NTI2MTA5M30.AXL9vIG4i_SlNPFq-211HoR_PubKg1TtCHo4kWR6kPU'

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Database types (will be auto-generated by Supabase later)
export interface Database {
  public: {
    Tables: {
      companies: {
        Row: {
          id: string
          name: string
          address: string
          city: string
          state: string
          zip: string
          quickbooks_realm_id: string | null
          quickbooks_connected: boolean
          quickbooks_company_name: string | null
          quickbooks_last_sync: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          address: string
          city: string
          state: string
          zip: string
          quickbooks_realm_id?: string | null
          quickbooks_connected?: boolean
          quickbooks_company_name?: string | null
          quickbooks_last_sync?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string
          city?: string
          state?: string
          zip?: string
          quickbooks_realm_id?: string | null
          quickbooks_connected?: boolean
          quickbooks_company_name?: string | null
          quickbooks_last_sync?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      bank_accounts: {
        Row: {
          id: string
          company_id: string
          name: string
          bank_name: string
          bank_city: string | null
          routing_number: string
          account_number: string
          signature: string
          default_layout_id: string | null
          background_color: string | null
          quickbooks_account_id: string | null
          sync_to_quickbooks: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          company_id: string
          name: string
          bank_name: string
          bank_city?: string | null
          routing_number: string
          account_number: string
          signature: string
          default_layout_id?: string | null
          background_color?: string | null
          quickbooks_account_id?: string | null
          sync_to_quickbooks?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          company_id?: string
          name?: string
          bank_name?: string
          bank_city?: string | null
          routing_number?: string
          account_number?: string
          signature?: string
          default_layout_id?: string | null
          background_color?: string | null
          quickbooks_account_id?: string | null
          sync_to_quickbooks?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      checks: {
        Row: {
          id: string
          company_id: string
          account_id: string
          account_holder_name: string
          account_holder_address: string
          account_holder_city: string
          account_holder_state: string
          account_holder_zip: string
          check_number: string
          date: string
          bank_name: string
          amount: string
          pay_to: string
          memo: string
          signature: string
          routing_number: string
          bank_account_number: string
          mail_to_name: string | null
          mail_to_address: string | null
          mail_to_suite: string | null
          mail_to_city: string | null
          mail_to_state: string | null
          mail_to_zip: string | null
          is_printed: boolean
          printed_date: string | null
          expense_category: string | null
          quickbooks_id: string | null
          quickbooks_vendor_id: string | null
          synced_to_quickbooks: boolean
          synced_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          company_id: string
          account_id: string
          account_holder_name: string
          account_holder_address: string
          account_holder_city: string
          account_holder_state: string
          account_holder_zip: string
          check_number: string
          date: string
          bank_name: string
          amount: string
          pay_to: string
          memo: string
          signature: string
          routing_number: string
          bank_account_number: string
          mail_to_name?: string | null
          mail_to_address?: string | null
          mail_to_suite?: string | null
          mail_to_city?: string | null
          mail_to_state?: string | null
          mail_to_zip?: string | null
          is_printed?: boolean
          printed_date?: string | null
          expense_category?: string | null
          quickbooks_id?: string | null
          quickbooks_vendor_id?: string | null
          synced_to_quickbooks?: boolean
          synced_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          company_id?: string
          account_id?: string
          account_holder_name?: string
          account_holder_address?: string
          account_holder_city?: string
          account_holder_state?: string
          account_holder_zip?: string
          check_number?: string
          date?: string
          bank_name?: string
          amount?: string
          pay_to?: string
          memo?: string
          signature?: string
          routing_number?: string
          bank_account_number?: string
          mail_to_name?: string | null
          mail_to_address?: string | null
          mail_to_suite?: string | null
          mail_to_city?: string | null
          mail_to_state?: string | null
          mail_to_zip?: string | null
          is_printed?: boolean
          printed_date?: string | null
          expense_category?: string | null
          quickbooks_id?: string | null
          quickbooks_vendor_id?: string | null
          synced_to_quickbooks?: boolean
          synced_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      custom_layouts: {
        Row: {
          id: string
          name: string
          fields: any // JSON
          drawing_elements: any // JSON
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          fields?: any
          drawing_elements?: any
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          fields?: any
          drawing_elements?: any
          created_at?: string
          updated_at?: string
        }
      }
    }
  }
}

