<template>
  <div class="layout-creator container py-4">
    <h2 class="mb-4">Check Layout Templates</h2>
    
    <div class="alert alert-info">
      <i class="bi bi-info-circle me-2"></i>
      Manage your custom check layouts here. The Original layout cannot be edited or deleted.
    </div>

    <!-- Custom Layouts Grid -->
    <div class="row">
      <div class="col-md-4 mb-4" v-for="layout in customLayouts" :key="layout.id">
        <div class="card layout-card">
          <div class="card-body">
            <h5 class="card-title">{{ layout.name }}</h5>
            <p class="card-text small text-muted">
              Fields: {{ layout.fields.length }}
            </p>
            <div class="btn-group btn-group-sm w-100">
              <button class="btn btn-outline-primary" @click="editLayout(layout.id)">
                <i class="bi bi-pencil"></i> Edit
              </button>
              <button class="btn btn-outline-danger" @click="deleteLayout(layout.id)" v-if="layout.id !== 'original'">
                <i class="bi bi-trash"></i> Delete
              </button>
            </div>
          </div>
        </div>
      </div>
      
      <!-- Add New Layout Card -->
      <div class="col-md-4 mb-4">
        <div class="card layout-card add-new-card" @click="createNewLayout">
          <div class="card-body text-center">
            <i class="bi bi-plus-circle display-1 text-primary"></i>
            <h5 class="card-title mt-3">Create New Layout</h5>
            <p class="card-text small text-muted">Start from scratch</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../stores/app'

const store = useAppStore()
const router = useRouter()

const customLayouts = computed(() => store.customLayouts.filter(l => l.id !== 'original'))

const editLayout = (layoutId: string) => {
  router.push(`/layout-editor/${layoutId}`)
}

const deleteLayout = (layoutId: string) => {
  if (!confirm('Are you sure you want to delete this layout?')) return
  store.deleteCustomLayout(layoutId)
}

const createNewLayout = async () => {
  const newLayout = {
    id: '', // Will be auto-generated by Supabase
    name: `Custom Layout ${customLayouts.value.length + 1}`,
    fields: [],
    drawingElements: []
  }
  
  await store.addCustomLayout(newLayout)
  
  // Get the newly created layout (it's the last one added)
  const createdLayout = customLayouts.value[customLayouts.value.length - 1]
  router.push(`/layout-editor/${createdLayout.id}`)
}
</script>

<style scoped>
.layout-card {
  transition: transform 0.2s, box-shadow 0.2s;
  cursor: pointer;
  height: 100%;
}

.layout-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
}

.add-new-card {
  border: 2px dashed #dee2e6;
  background-color: #f8f9fa;
}

.add-new-card:hover {
  border-color: #0d6efd;
  background-color: #e7f1ff;
}
</style>
